name: 1. Main Workflow - Request for Approval

on:
  push:
    branches:
      - main

jobs:
  build-and-request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run initial steps
        run: |
          echo "Running initial build and test steps..."
          # 在这里放置您的构建、测试等命令
          echo "Steps before approval complete."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          pip install requests

      - name: Send approval message
        env:
          RECEIVE_ID: ${{ secrets.RECEIVE_ID }}
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          RUN_ID: ${{ github.run_id }}
        run: |
          python scripts/send.py